[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

## ОТДЕЛЬНЫЙ РЕДИРЕКТ ДЛЯ sitemap.xml (ДОЛЖЕН БЫТЬ ПЕРВЫМ!)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200

## Главный редирект SPA (Vue) - ДОЛЖЕН БЫТЬ ПОСЛЕДНИМ!
[[redirects]]
   from = "/*"
   to = "/index.html"
   status = 200
