[build]
  command = "npm run build"
  functions = "netlify/functions"
  publish = "dist"

## ОТДЕЛЬНЫЙ РЕДИРЕКТ ДЛЯ sitemap.xml (он должен быть ПЕРВЫМ)
[[redirects]]
  from = "/sitemap.xml"
  to = "/sitemap.xml"
  status = 200
  force = true

## SPA-редирект для Vue (ОБЯЗАТЕЛЬНО оставьте его ПОСЛЕДНИМ!)
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
